### ISSUE TITLE
Western Championship is not a CubingUSA supported competition

### ISSUE THREAD

**Issue by timreyn** [cubingusa/org#136]
Don't display it as such on /regional or the regional psych sheet.

**Comment by ToastyKen** [comment]
So we've decided the event will still be called "CubingUSA Western Championship 2018", but we want to add a note to the effect of "hosted by Berkeley Cube Club", with an optional ", in partnership with CubingUSA".

**Comment by jpbulman** [comment]
Can this be closed now?
