### ISSUE TITLE
Streaming Info

### ISSUE THREAD

**Issue by timreyn** [cubingusa/org#161]
Get streaming link and schedule posted.

**Comment by ToastyKen** [comment]
Make sure to note 3x3 Finals start time with time zone: Sunday July 29, 4:00 PM MDT (UTC-6)

**Comment by timreyn** [comment]
We don't have a streaming schedule, so I'll go ahead and post a link to mentalblock.tv to the home page.

I'll also iframe the stream on the homepage, as suggested by Calvin and Devin.  But I'll wait to push that until the staff comp starts on Thursday.  I'll prepare that in a separate PR.
