### ISSUE TITLE
States under 'Edit User' has two drop down arrows

### ISSUE THREAD

**Issue by jpbulman** [cubingusa/org#191]
The state selection dropdown in the edit user [page](https://cubingusa.org/edit) has two dropdown arrows. I think getting rid of the 'custom select' class [here](https://github.com/cubingusa/org/blob/b9856a44d7bd5f619a11ccf2ef956c252a94852c/src/templates/edit_user.html#L47) should work. Somehow I accidentally closed #190 twice, so I just made a new thread

**Comment by timreyn** [comment]
This seems to be working for me now?  @jpbulman please reopen if you're still seeing this.
