### ISSUE TITLE
Regional Champions list always shows current year, not champion year

### ISSUE THREAD

**Issue by ToastyKen** [cubingusa/org#200]
The currently regional champions list says 2019 instead of 2018, because it's a variable that auto-updates to the current year, even though the contents are still from 2018.

**Comment by ToastyKen** [comment]
On this page:

"2019 Regional Championships" is correct
but
"2019 3x3x3 Cube Regional Champions"
should say
"2018 3x3x3 Cube Regional Champions"
and presumably we'll soon need year switching support

**Comment by timreyn** [comment]
Thanks for pointing that out!

@jpbulman do you want to take a look at this issue?

**Comment by jpbulman** [comment]
Sure! Should it say the previous year's champions until one of the championships has been completed, or wait until all of them are finished?

**Comment by ToastyKen** [comment]
I think ideally it should show this year's champs once one has finished, with option to go back and browse previous years?
