### ISSUE TITLE
Edit users page is somewhat visible to non admins

### ISSUE THREAD

**Issue by jpbulman** [cubingusa/org#213]
While looking at #201 , I visited https://cubingusa.org/admin/edit_users and saw something odd. The edit users admin filter box comes up for me (even though I'm not an admin), but not the table. I duplicated this locally and found that anyone who is a delegate will get this strange formatting, but a person with no permissions (an average competitor) will just get redirected back home. I'll try and poke around, but the permission controlling for edit users does not seem to be in the handler, so if anyone has suggestions or a fix, feel free to chime in. 

Not a dangerous issue since the table does not appear, which means delegates can't just edit users freely.
 
![users](https://user-images.githubusercontent.com/12652192/59966219-14de9b00-94e7-11e9-83e7-fcdf02ffac73.png)

**Comment by timreyn** [comment]
Hey JP, good catch.

This is configured here: https://github.com/cubingusa/org/blob/master/cubingusa.py#L75  Key is "AllRoles()".

It probably makes sense to set this to the same set of users that can actually edit users -- this is the handler for the async fetch: https://github.com/cubingusa/org/blob/b9856a44d7bd5f619a11ccf2ef956c252a94852c/src/handlers/admin/edit_users.py#L32

**Comment by jpbulman** [comment]
Having some annoying git problems, so just ignore the referenced commit right before the pr.

**Comment by timreyn** [comment]
Addressed in #240.
