### ISSUE TITLE
Add Nats 2019 registration opening times

### ISSUE THREAD

**Issue by ToastyKen** [cubingusa/org#219]
Can we add registration opening times to the schedule page?

Thursday, August 1
Registration / Help Desk opens at 10am
[events]

Friday, August 2
Registration / Help Desk opens at 8am
[events]

Saturday, August 3
Registration / Help Desk opens at 8am
[events]

Probably don't need it for Sunday.

**Comment by ToastyKen** [comment]
@timreyn Can you confirm that these are correct?

**Comment by timreyn** [comment]
Will do tonight.  @ToastyKen we have staff assigned to help desk starting at 8 AM on Thursday.  Let's say 9:00 it opens, to give some slack for getting set up and ready?
