### ISSUE TITLE
Duplicative state records

### ISSUE THREAD

**Issue by khkellis** [cubingusa/org#256]
**Action taken**: I just changed from Maryland to California on CubingUSA. 

**Expected result:** None of my solves are records (thanks Max!), so none should be on the CubingUSA page.

**Actual result**: I see my old MD state records on the California page, duplicated with Max's OH results, for both Single and Average.

<img width="918" alt="Screen Shot 2023-11-07 at 6 15 00 PM" src="https://github.com/cubingusa/org/assets/27914581/506c4837-b74e-423e-94c5-fb0906070942">

**Comment by timreyn** [comment]
Thanks Keaton!

I pushed a change earlier that automatically clears the is_state_record bit when you change states. State records get updated nightly, so this will get cleared up overnight, and should not happen again in the future.

I'll mark this resolved once your OH state record is removed.
