### ISSUE TITLE
Logging in should require logging in

### ISSUE THREAD

**Issue by jbmertens** [cubingusa/org#35]
Logging in, or hitting pages like /nationals that require logging in, will automatically log me in to whichever WCA account I am signed in on (or prompt me to log in otherwise). If I wanted to to log in as someone else (use case: parents managing accounts for multiple kids), I would have to go to the WCA website and log out there as well, which isn't an obvious step.

(@jfly) This might be best solved on the WCA's end with a prompt to "log in as [user already logged in as]" vs "log in as someone else" rather than an invisible redirect.

**Comment by timreyn** [comment]
Very good point, but I'll note that the nationals page is only temporarily locked down, and the only readily-accessible page that will require login long-term will be /edit, so for the most part this won't actually matter.  It's still a good point though.

**Comment by jfly** [comment]
@jbcm627, do you have an example of an oauth flow that you like? It's always nice to copy someone else's UX than invent our own =)

**Comment by jbmertens** [comment]
Hm, Google is probably the only other example I use. For a browser in which I've only ever signed into one account, I seem to be invisibly redirected. For a browser in which I've used multiple accounts, it will ask (and remember and suggest "Signed out" accounts):
![capture](https://user-images.githubusercontent.com/964048/34283577-817a0d46-e69a-11e7-93da-434b7a8593f5.PNG)
So one solution is to try to recognize when an account needs to be chosen. Another "easier" option is just to always prompt users like this.

**Comment by jfly** [comment]
Thanks @jbcm627! This feels like it's going to be a lot of work with fairly little reward, so I'm not making any promises we'll work on this anytime soon, but it definitely sounds like a nice thing to have.

**Comment by timreyn** [comment]
Per @jfly 's comments I think this is probably better done on the WCA OAuth side rather than any CubingUSA changes.
