### ISSUE TITLE
Support foreigners

### ISSUE THREAD

**Issue by ToastyKen** [cubingusa/org#60]
https://cubingusa.org/edit page lists US states and territories but does not allow foreigners like Feliks to specify that they are not US residents.

We need to provide either "non US resident" option.

**Comment by ToastyKen** [comment]
Actually, I noticed the first option is empty string. Is that selectable? If so, I think we should rephrase it as "Non-US?"

**Comment by timreyn** [comment]
Yeah, the first option is selectable.  Agreed with rewording.
