### ISSUE TITLE
Specify that qualification times are <=, not <

### ISSUE THREAD

**Issue by timreyn** [cubingusa/org#74]

**Comment by jfly** [comment]
For consistency, it might be nice to use "better than" rather than "better than or equal to". See https://github.com/thewca/worldcubeassociation.org/pull/2274 for a relevant change for cutoffs.

**Comment by ToastyKen** [comment]
After discussion, because we already started using better than or equal to, we're going to stick with that for this year.  We might want to change that for next year.

**Comment by jfly** [comment]
I get that you don't want to change the effective qualification times, but that doesn't have to happen, right?
For example, currently the cutoff for 333 is `<= 30 seconds average`, but you could change that to `< 30.01 seconds average`, right?

**Comment by timreyn** [comment]
< 30.01 seconds seems less clear to competitors. I don't really want to
change everything on the events page to add 0.01 seconds.

Can we just proceed like this for this year, and then next year once the
WCA site has support for qualification times, follow the standard set there?

**Comment by jfly** [comment]
Sounds good!
