### ISSUE TITLE
Local competition notifications

### ISSUE THREAD

**Issue by ToastyKen** [cubingusa/org#88]
I think we used to have a notification system for competitions near you.. that we got rid of I think?

Would be nice to re-implement that.

**Comment by jfly** [comment]
I think it makes more sense for this to go on the wca website, unless there
is anything special cubingusa can do here? (see https://github.com/thewca/worldcubeassociation.org/issues/114)

**Comment by timreyn** [comment]
+1 to @jfly .  Jeremy, is this something the WST is looking into addressing in the near future?  I think this has been a longstanding FR.

The old system was never automated IIUC.  I think Bryan just sent out emails every so often.

**Comment by jfly** [comment]
@pedrosino is hopefully going to find some time to work on https://github.com/thewca/worldcubeassociation.org/issues/732 soon, which then opens up the possibility of working on https://github.com/thewca/worldcubeassociation.org/issues/114.

**Comment by timreyn** [comment]
Closing this since I don't think this is in scope for cubingusa.  Kenneth, feel free to re-open if you disagree.
