### ISSUE TITLE
Scorecards

### ISSUE THREAD

**Issue by timreyn** [cubingusa/org#92]
Figure out whether the best option for Nationals is to have our own scorecards, or to use an external site.

**Comment by jfly** [comment]
CC-ing @jonatanklosko just so he can keep an eye on this.

**Comment by timreyn** [comment]
@jonatanklosko, is it possible to use groupifier's scorecards with custom groups?

**Comment by jonatanklosko** [comment]
Hey @timreyn, it's not something supported at the moment. In the future groupifier and scorecards app will be two separate entities, so you would be able to use any tool for creating groups and saving them to the WCA website, then generate scorecards from that. At the moment the WCA website don't store registrations for all competitions (i.e. from some external registration platforms), that's why Groupifier doesn't save/read all task assignment information to/from WCIF, and does everything by itself.

**Comment by timreyn** [comment]
Awesome, thanks for the info.  Would it be safe for us to count on having this by the end of June?

**Comment by jonatanklosko** [comment]
@jfly do we plan to have wca-live ready by then? If so, @timreyn it would mean yes (generating scorecards for each round). Either way, that's quite a long time and I already have scorecards generation, so we should be able to figure something out by then =)

**Comment by timreyn** [comment]
Great.  We'll also have the ability to output WCIF including group assignments from the cubingusa site, which could be a backup plan if all of the requirements on the WCA site and wca-live aren't ready yet.

**Comment by jfly** [comment]
> @jfly do we plan to have wca-live ready by then?

@jonatanklosko, I kind of doubt wca-live will be ready by then. I don't think any of this is related to wca-live, though, and I think we can commit to having the WCA website wcif support and splitting @jonatanklosko's app into 2 apps by then!

**Comment by jonatanklosko** [comment]
@jfly talking about wca-live I thought about subsequent rounds specifically (2nd, 3rd, ...), I don't think we will have the results stored on the WCA website without it.

**Comment by jfly** [comment]
Ah, sorry for not putting all my thinking in text. Here's my thinking: Tim has to find a solution for generating groups and scorecards for subsequent rounds of US Nationals. That means he is already going to have to import data from Cubecomps in his own Python software. If we provide the WCA APIs, he could then send that data over to the WCA website, and be able to use your scorecard generation software.
